# Cloudflare Pages + Functions Configuration
# This file configures both local development and production deployment

name = "farmers-boot"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages Functions configuration
pages_build_output_dir = "frontend/dist"

## Local D1 binding (so `env.DB` is a D1 binding during local dev)
[[d1_databases]]
binding = "DB"
database_id = "106c9d2b-c97a-483e-9eff-e713150d8a9a"
database_name = "farmers-boot-local"

# Preview environment (for testing)
[env.preview]
# Use production database for preview deployments
[[env.preview.d1_databases]]
binding = "DB"
database_name = "farmers-boot-prod"
database_id = "96ba79d2-c66e-4421-9116-3d231666266c"

# Production environment
[env.production]
# Environment variables for production
# These should be set in Cloudflare Pages dashboard

# External services
VITE_MAPBOX_TOKEN = "your-mapbox-token"

# JWT Secret for authentication (set in Cloudflare Pages dashboard)
JWT_SECRET = "your-production-jwt-secret-change-this"

# Monitoring
SENTRY_DSN = "your-sentry-dsn"

# Pages URL (auto-populated by Cloudflare)
CF_PAGES_URL = "https://your-pages-url.pages.dev"

# D1 Database for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "farmers-boot-prod"
database_id = "96ba79d2-c66e-4421-9116-3d231666266c"

# R2 Storage for production (optional - commented out for now)
# [[env.production.r2_buckets]]
# binding = "STORAGE"
# bucket_name = "farmers-boot-prod"

# KV Storage for rate limiting (optional - commented out for now)
# [[env.production.kv_namespaces]]
# binding = "RATE_LIMIT_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"