# Cloudflare Pages + Functions Configuration
# This file configures both local development and production deployment

name = "farmers-boot"
compatibility_date = "2024-01-01"

# Local development environment
[env.local]
# Local environment variables (can be overridden by .env file)
# Supabase
SUPABASE_URL = "http://localhost:54321"
SUPABASE_SERVICE_ROLE_KEY = "your-local-service-role-key"

# External services
VITE_SUPABASE_URL = "http://localhost:54321"
VITE_SUPABASE_ANON_KEY = "your-local-anon-key"
VITE_MAPBOX_TOKEN = "your-mapbox-token"

# Local development settings
CF_PAGES_URL = "http://localhost:8788"

# KV namespace for local development (optional)
[[env.local.kv_namespaces]]
binding = "RATE_LIMIT_KV_LOCAL"
id = "local-kv-namespace"
preview_id = "local-kv-namespace"

# Production environment
[env.production]
# Environment variables for production
# These should be set in Cloudflare Pages dashboard

# Supabase
SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"

# External services
VITE_SUPABASE_URL = "https://your-project.supabase.co"
VITE_SUPABASE_ANON_KEY = "your-anon-key"
VITE_MAPBOX_TOKEN = "your-mapbox-token"

# Monitoring
SENTRY_DSN = "your-sentry-dsn"

# Webhooks
WEBHOOK_SECRET = "your-webhook-secret"

# Rate limiting
RATE_LIMIT_KV = "your-kv-namespace-id"

# Pages URL (auto-populated by Cloudflare)
CF_PAGES_URL = "https://your-pages-url.pages.dev"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Function bindings for Pages Functions
pages_build_output_dir = "frontend/dist"

# Pages Functions configuration
functions = "functions"