-- POSTGRES-ONLY MIGRATION (archived)
-- NOTE: This migration contains Postgres-specific DDL (UUIDs, jsonb, timestamptz,
-- and RLS-compatible schema). Cloudflare D1 is SQLite-like and uses a different
-- SQL dialect (INTEGER AUTOINCREMENT, TEXT, DATETIME). Do NOT run this file
-- against a D1 database.
--
-- For Cloudflare D1, the canonical D1-compatible schema is provided in
-- `schema.sql` at the project root. Apply it with:
--
--   wrangler d1 execute <your-d1-database> --file=schema.sql
--
-- Keep Postgres/Supabase migrations in a separate archive if you still need
-- to support a Postgres deployment.

-- Original filename: 0002_core_inventory_finance.sql
