-- POSTGRES-ONLY MIGRATION (archived)
-- NOTE: This migration contains row-level security (RLS) policies that rely on
-- Supabase/Postgres' `auth.uid()` helper and procedural DO blocks. Cloudflare D1
-- does not support Postgres extensions, RLS, or the `auth.uid()` helper. Do NOT
-- run this file against a D1 database.
--
-- For D1, implement access control at the application layer (Cloudflare
-- Functions) by validating JWTs and passing user ids to queries (e.g. using
-- parameterized WHERE clauses against `env.DB.prepare(...)`). The D1 schema
-- is provided in `schema.sql`.

-- Original filename: 0003_operations_idempotency_and_rls.sql
